### ISSUE TITLE
Force problem

### ISSUE THREAD

**Issue by Jorrit076** [codebuds33/webp-converter#1]
Hello,

I think there is something wrong with the force option. When I enable it it gives an exeption.
I looked inside the code and I think you need to change this:
![image](https://user-images.githubusercontent.com/14159071/197477263-c7179b75-c7fa-4d38-a648-0763c1e50301.png)

To this:
![image](https://user-images.githubusercontent.com/14159071/197477350-83571910-30a1-49cd-98fb-5060cd5074dd.png)

**Comment by DennisCodeBuds** [comment]
Hey thanks for creating the issue, this has just been fixed in 0.5.1, I also added some tests and a new version for https://github.com/codebuds33/webp-conversion-bundle that takes the update into account
